[package]
name = "databas_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
crc32-v2 = "0.0.4"

[dev-dependencies]
tempfile = "3.25.0"
fastrand = "2.3.0"
