[package]
name = "databas_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
fastrand = "2.3.0"

[dev-dependencies]
tempfile = "3.25.0"
